# Generated by Django 3.2.7 on 2021-12-26 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0003_auto_20211202_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_personal_interest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MentoringProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_enroll_on', models.BooleanField(default=False)),
                ('is_program_started', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='user_app.profile')),
                ('moderator', models.ManyToManyField(related_name='moderator', to='user_app.Profile')),
                ('trainer', models.ManyToManyField(related_name='trainer', to='user_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='mentoring_app.feature')),
                ('userresponse_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userresponse_profile', to='user_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserEnroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_submited', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('mentee', models.ManyToManyField(related_name='mentee', to='user_app.Profile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='user_app.profile')),
                ('mentoring_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_program', to='mentoring_app.mentoringprogram')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='user_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MmTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('is_done', models.BooleanField(default=False)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mmtask_mentee', models.ManyToManyField(related_name='mmtask_mentee', to='user_app.Profile')),
                ('mmtask_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmtask_mentor', to='user_app.profile')),
                ('mmtask_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmtask_program', to='mentoring_app.mentoringprogram')),
            ],
        ),
        migrations.CreateModel(
            name='MmChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mmchat_mentee', models.ManyToManyField(related_name='mmchat_mentee', to='user_app.Profile')),
                ('mmchat_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmchat_mentor', to='user_app.profile')),
                ('mmchat_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmchat_program', to='mentoring_app.mentoringprogram')),
                ('mmchat_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmchat_receiver', to='user_app.profile')),
                ('mmchat_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmchat_sender', to='user_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_program', to='mentoring_app.mentoringprogram'),
        ),
    ]
