# Generated by Django 3.2.7 on 2021-12-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring_app', '0002_auto_20211226_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userenroll',
            name='mentoring_program',
        ),
    ]
