# Generated by Django 3.2.7 on 2021-12-27 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring_app', '0003_remove_userenroll_mentoring_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenroll',
            name='userenroll_program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userenroll_program', to='mentoring_app.mentoringprogram'),
        ),
    ]
