# Generated by Django 3.2.7 on 2021-12-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20211202_1304'),
        ('mentoring_app', '0004_userenroll_userenroll_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_program', to='mentoring_app.mentoringprogram'),
        ),
        migrations.AlterField(
            model_name='mentoringprogram',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='user_app.profile'),
        ),
        migrations.AlterField(
            model_name='mmchat',
            name='mmchat_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmchat_mentor', to='user_app.profile'),
        ),
        migrations.AlterField(
            model_name='mmchat',
            name='mmchat_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmchat_program', to='mentoring_app.mentoringprogram'),
        ),
        migrations.AlterField(
            model_name='mmchat',
            name='mmchat_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmchat_receiver', to='user_app.profile'),
        ),
        migrations.AlterField(
            model_name='mmchat',
            name='mmchat_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmchat_sender', to='user_app.profile'),
        ),
        migrations.AlterField(
            model_name='mmtask',
            name='mmtask_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmtask_mentor', to='user_app.profile'),
        ),
        migrations.AlterField(
            model_name='mmtask',
            name='mmtask_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmtask_program', to='mentoring_app.mentoringprogram'),
        ),
        migrations.AlterField(
            model_name='userenroll',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='user_app.profile'),
        ),
        migrations.AlterField(
            model_name='userenroll',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='user_app.profile'),
        ),
        migrations.AlterField(
            model_name='userenroll',
            name='userenroll_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userenroll_program', to='mentoring_app.mentoringprogram'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='mentoring_app.feature'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='userresponse_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userresponse_profile', to='user_app.profile'),
        ),
    ]
