# Generated by Django 3.2.7 on 2021-12-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring_app', '0005_auto_20211227_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringprogram',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
