# Generated by Django 3.2.7 on 2021-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring_app', '0006_mentoringprogram_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringprogram',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
