# Generated by Django 3.2.7 on 2021-12-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring_app', '0007_mentoringprogram_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userenroll',
            name='is_rejected',
        ),
    ]
