# Generated by Django 3.2.7 on 2022-01-02 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20211202_1304'),
        ('mentoring_app', '0008_remove_userenroll_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoringprogram',
            name='moderator',
            field=models.ManyToManyField(blank=True, related_name='moderator', to='user_app.Profile'),
        ),
        migrations.AlterField(
            model_name='mentoringprogram',
            name='trainer',
            field=models.ManyToManyField(blank=True, related_name='trainer', to='user_app.Profile'),
        ),
        migrations.RemoveField(
            model_name='mmchat',
            name='mmchat_mentee',
        ),
        migrations.AddField(
            model_name='mmchat',
            name='mmchat_mentee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmchat_mentee', to='user_app.profile'),
        ),
        migrations.RemoveField(
            model_name='mmtask',
            name='mmtask_mentee',
        ),
        migrations.AddField(
            model_name='mmtask',
            name='mmtask_mentee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmtask_mentee', to='user_app.profile'),
        ),
        migrations.AlterField(
            model_name='userenroll',
            name='mentee',
            field=models.ManyToManyField(blank=True, related_name='mentee', to='user_app.Profile'),
        ),
    ]
