# Generated by Django 3.2.7 on 2021-12-03 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20211202_1304'),
        ('inbox_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('redirect_url', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reciver', models.ManyToManyField(blank=True, to='user_app.Profile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
