# Generated by Django 3.2.7 on 2021-12-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20211202_1304'),
        ('inbox_app', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='reciver',
        ),
        migrations.AddField(
            model_name='notification',
            name='reciver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.profile'),
        ),
    ]
