# Generated by Django 3.2.7 on 2021-12-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox_app', '0003_auto_20211203_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
