# Generated by Django 3.2.7 on 2021-12-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finished_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
